# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1caeabf7-149f-4cdb-86cd-ccc95dbc1441'
  imageRepository: 'dsmsgosampleapp'
  containerRegistry: 'desattiracr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'desattiracrac5f-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: KubernetesManifest@0
        name: bake
        inputs:
          action: 'bake'
          helmChart: 'charts/sampleapp'
          releaseName: 'abc'
          overrideFiles: 'somevaluesfile.yml'
          overrides: |
            fullNameOverride: xyz
          
      - task: KubernetesManifest@0
        displayName: Deploy to Kubernetes cluster
        inputs:
          action: deploy
          kubernetesServiceConnection: desattiraks-dev9aa9
          manifests: $(bake.manifestsBundle)