apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: harikaakseeflow 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: harikaakseeflow 
    spec:
      containers:
        - name: harikaakseeflow 
          image: desattiracr.azurecr.io/harikaakseeflow 
          ports:
          - containerPort: 80